Exercici 1

In [1]:
# Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. 
# Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

import numpy as np   
  

axis0 = int(input("número de files:"))
axis1 = int(input("número de columnes:")) # dos dimensions
array_1D = np.random.randn(axis0)
array_2D = np.random.randn(axis0,axis1)

def resum_estadístic(axis1):
    if axis1 == 0:
        print(array_1D)
        print("mitjana aritmètica:", np.mean(array_1D))
        print("mediana:", np.median(array_1D))
        print("variança:", np.var(array_1D))
        print("desviació estàndard:", np.std(array_1D))
    elif axis1 > 0:
        print(array_2D, "ERROR: Array de dos dimensions!")

resum_estadístic(axis1)

número de files:3
número de columnes:0
[-0.2333661  -0.47282613 -0.44532319]
mitjana aritmètica: -0.38383847460686543
mediana: -0.44532318919032976
variança: 0.011447036183328221
desviació estàndard: 0.10699082289303238


In [2]:
# Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. 
# Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

# Resum estadístic amb PANDAS

import numpy as np
import pandas as pd
  

axis0 = int(input("número de files:"))
axis1 = int(input("número de columnes:")) # dos dimensions
array_1D = np.random.randn(axis0)
array_2D = np.random.randn(axis0,axis1)
dataframe = pd.DataFrame(array_1D)

def resum_estadístic(axis1):
    if axis1 == 0:
        print(array_1D)
        print(dataframe.describe())
    elif axis1 > 0:
        print(array_2D, "ERROR: Array de dos dimensions!")

resum_estadístic(axis1)

número de files:3
número de columnes:0
[ 0.04517481 -0.27624416  0.47643736]
              0
count  3.000000
mean   0.081789
std    0.377674
min   -0.276244
25%   -0.115535
50%    0.045175
75%    0.260806
max    0.476437


Exercici 2

In [3]:
# Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

import numpy as np  

N = int(input("número de files i columnes:"))

def quadrat(N):
    if N > 0:
        print(np.random.randint(0,100, size=(N, N)))
    else:
        print("ERROR!!!")

quadrat(N)


número de files i columnes:4
[[32 78 30 68]
 [26 33 95 26]
 [88 96 74  5]
 [78 65 12 90]]


Exercici 3

In [4]:
# Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

# amb PANDAS

import numpy as np
import pandas as pd

N = int(input("número de files:"))
M = int(input("número de columnes:"))
taula = (np.random.randn(N, M))
df = pd.DataFrame(taula)
print(df)

def totals(N, M):
    if N > 0 and M > 0:
        print("totals per columna:", df.sum())
        print("totals per fila:", df.sum(axis=1))

    else:
        print("ERROR!!!")

totals(N, M)




número de files:4
número de columnes:5
          0         1         2         3         4
0  0.601599 -0.495798  0.875886  0.065048 -0.135354
1  1.443939 -0.840304 -0.000046 -1.362874 -0.086135
2  0.708255  0.115308  0.339592 -1.469009 -0.662444
3 -1.085779  1.769215 -1.687960 -1.043886  2.085534
totals per columna: 0    1.668014
1    0.548421
2   -0.472528
3   -3.810721
4    1.201601
dtype: float64
totals per fila: 0    0.911381
1   -0.845421
2   -0.968298
3    0.037124
dtype: float64


In [5]:
# amb NUMPY

import numpy as np
import pandas as pd

N = int(input("número de files:"))
M = int(input("número de columnes:"))
taula = (np.random.randn(N, M))
df = pd.DataFrame(taula)
print(df)

def totals_numpy(N, M):
    if N > 0 and M > 0:
        print("totals per columna:", np.sum(taula, axis=0))
        print("totals per fila:", np.sum(taula, axis=1))

    else:
        print("ERROR!!!")

totals_numpy(N, M)


número de files:4
número de columnes:5
          0         1         2         3         4
0  0.472600  0.033330 -1.146676 -0.057624  0.758561
1  0.501744 -0.332373 -0.003418  0.118753  0.152452
2 -0.859114 -0.032043  0.399974 -0.931357  1.858019
3 -1.042961 -0.614760  0.261109 -0.434337 -0.574110
totals per columna: [-0.92773116 -0.94584565 -0.48901099 -1.30456457  2.19492137]
totals per fila: [ 0.0601914   0.43715746  0.43547935 -2.40505922]


Exercici 4

In [6]:
# Implementa manualment una funció que calculi el coeficient de correlació.
# Informa-te'n sobre els seus usos i interpretació.

import numpy as np

Dades = int(input("total dades:"))
valors_variable_1 = np.random.randn(Dades)
valors_variable_2 = np.random.randn(Dades)


def Coef_Correlació(Dades):
    if Dades > 0:
        print(valors_variable_1)
        print(valors_variable_2)
        print("R:", np.corrcoef(valors_variable_1, valors_variable_2))
       
    else:
        print("ERROR: no hi ha dades suficients")

Coef_Correlació(Dades)


total dades:10
[-1.34198043 -0.51434794 -0.28221702  0.80449306 -0.26857624 -1.21992855
  0.11615271  1.40354612 -0.3021953   0.40983575]
[ 0.64261358  0.12205065  1.90470089 -0.16126326 -0.0760222  -0.57661434
  1.78187115 -0.45446025  0.07129275  0.41093211]
R: [[ 1.         -0.10922657]
 [-0.10922657  1.        ]]
